# Generated by Django 2.2.6 on 2019-11-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20191118_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='p_library.Publisher'),
        ),
    ]
